// <auto-generated />
using System;
using Example.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Example.WebApi.Migrations
{
    [DbContext(typeof(ProductContex))]
    [Migration("20220224194442_SeedProductData")]
    partial class SeedProductData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Example.WebApi.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<DateTime>("createdDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TV",
                            Price = 3000m,
                            Stock = 50,
                            createdDate = new DateTime(2022, 2, 21, 22, 44, 42, 370, DateTimeKind.Local).AddTicks(8008)
                        },
                        new
                        {
                            Id = 2,
                            Name = "Table",
                            Price = 1750m,
                            Stock = 750,
                            createdDate = new DateTime(2022, 2, 9, 22, 44, 42, 371, DateTimeKind.Local).AddTicks(7821)
                        },
                        new
                        {
                            Id = 3,
                            Name = "Keyboard",
                            Price = 100m,
                            Stock = 125,
                            createdDate = new DateTime(2022, 2, 23, 22, 44, 42, 371, DateTimeKind.Local).AddTicks(7844)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
